version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos-app
    volumes:
      - .:/var/www/
    working_dir: /var/www/pos-system
    depends_on:
      - mysql
    ports:
      - 9000:9000

  web:
    image: nginx:alpine
    container_name: pos-web
    volumes:
    # ./pos-system (on your host machine) /var/www/pos-system (inside the container)
      - ./pos-system:/var/www/pos-system
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: pos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: